/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    // MANUAL ENTRY (T-016 / T-021) — pending first `bun sst dev` regen.
    // The secrets are real (declared in `infra/secrets.ts` and linked
    // in `infra/api.ts`); this stanza is here so typecheck passes
    // before SST has been re-run locally to refresh this file. Safe
    // to delete on the next regen — it'll come back identical.
    // Throws on `.value` access in production (secret undeclared) —
    // see `application/auth/e2e-bootstrap/postE2EAuthLoginHandler.ts`
    // for the try/catch that maps the throw to 503.
    "E2E_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PLANETSCALE_DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WORKOS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WORKOS_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WORKOS_COOKIE_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WORKOS_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "api-core": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}

import "sst"
export {}