/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "WORKOS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WORKOS_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WORKOS_COOKIE_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WORKOS_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}