// Slice 1 — auth-and-orgs schema.
//
// Authoritative spec: `specs/ai-data-room/auth-and-orgs/design.md` §Data model.
// Mirrors WorkOS identity (see ADR-001). Audit trail is append-only-by-
// convention at v0.1; SOC 2 entry will tighten to trigger-enforced.
//
// First migration (`migrations/0000_init_auth_and_orgs.sql`) generated by
// T-003. T-005 augments it (`migrations/0001_postgres_specific_constraints.sql`)
// with the Postgres-specific bits the DSL handles via escape hatches:
//
//   - `citext` for `users.email` and `invitations.email` (declared via
//     `customType` below; the `CREATE EXTENSION citext` is prepended to
//     the 0001 migration by hand because drizzle-kit doesn't emit
//     extension-creation statements).
//   - Partial unique on `users(email) WHERE lifecycle_state <> 'deleted'`
//     (`uniqueIndex().where(...)`).
//   - Single-owner-per-org partial unique on
//     `org_memberships(org_id) WHERE role = 'owner'`.

import {
  boolean,
  customType,
  index,
  inet,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

// `citext` — case-insensitive text. Postgres-specific, requires the
// `citext` extension to be installed (created in
// `migrations/0001_*.sql`). Drizzle-kit doesn't ship a citext column
// helper, so we declare it via `customType` here so the schema reads
// `citext("email")` like any other column. The data shape is just
// string at the JS boundary — Postgres handles the case-insensitive
// comparison server-side.
//
// This means equality joins / `WHERE email = 'X'` are case-insensitive
// without needing `LOWER()` on every read, which is what FR2 actually
// expects ("alice@x.com" must collide with "ALICE@x.com" at signup).
const citext = customType<{ data: string }>({
  dataType: () => "citext",
});

// ── Enums ──────────────────────────────────────────────────────────────
export const orgStatus = pgEnum("org_status", [
  "active",
  "suspended",
  "deleted",
]);

export const userLifecycleState = pgEnum("user_lifecycle_state", [
  "active",
  "suspended",
  "deleted",
]);

export const orgRole = pgEnum("org_role", ["owner", "editor", "viewer"]);

export const externalGrantStatus = pgEnum("external_grant_status", [
  "active",
  "revoked",
  "expired",
]);

export const invitationKind = pgEnum("invitation_kind", [
  "internal",
  "external",
]);

export const invitationRole = pgEnum("invitation_role", ["editor", "viewer"]);

export const invitationState = pgEnum("invitation_state", [
  "pending",
  "accepted",
  "revoked",
  "expired",
]);

export const auditOutcome = pgEnum("audit_outcome", ["success", "failure"]);

// ── Tables ─────────────────────────────────────────────────────────────
export const organizations = pgTable(
  "organizations",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    workosOrgId: text("workos_org_id").notNull(),
    name: text("name").notNull(),
    slug: text("slug").notNull(),
    status: orgStatus("status").notNull().default("active"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    workosOrgIdx: uniqueIndex("organizations_workos_org_id_key").on(
      t.workosOrgId,
    ),
    slugIdx: uniqueIndex("organizations_slug_key").on(t.slug),
  }),
);

export const users = pgTable(
  "users",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    workosUserId: text("workos_user_id").notNull(),
    // Nullable: gets nulled by the GDPR scrub on lifecycle=deleted
    // (NFR9). The partial unique index below enforces uniqueness only
    // for non-deleted rows so a fresh signup with a previously-deleted
    // address doesn't collide with the tombstone.
    email: citext("email"),
    fullName: text("full_name"),
    lifecycleState: userLifecycleState("lifecycle_state")
      .notNull()
      .default("active"),
    emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }),
    mfaEnrolledAt: timestamp("mfa_enrolled_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    workosUserIdx: uniqueIndex("users_workos_user_id_key").on(t.workosUserId),
    // Partial unique on email for non-deleted rows. NULLs don't conflict
    // with NULLs in Postgres, but being explicit about the predicate
    // keeps the intent legible to a SOC 2 reviewer and survives any
    // future change to the deletion path that might keep the email
    // column non-null (e.g. obfuscation rather than NULL).
    emailActiveIdx: uniqueIndex("users_email_active_key")
      .on(t.email)
      .where(sql`lifecycle_state <> 'deleted'`),
  }),
);

export const orgMemberships = pgTable(
  "org_memberships",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    role: orgRole("role").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    orgUserIdx: uniqueIndex("org_memberships_org_user_key").on(
      t.orgId,
      t.userId,
    ),
    // FR1 invariant: at most one `owner` per organisation. Partial
    // unique on `(org_id) WHERE role = 'owner'` is the cheapest way to
    // enforce it at the DB layer — admins / internals are unconstrained
    // beyond the (org, user) uniqueness above.
    singleOwnerIdx: uniqueIndex("org_memberships_single_owner_key")
      .on(t.orgId)
      .where(sql`role = 'owner'`),
  }),
);

export const externalAccessGrants = pgTable(
  "external_access_grants",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id),
    opportunitySlug: text("opportunity_slug").notNull(),
    grantedBy: uuid("granted_by")
      .notNull()
      .references(() => users.id),
    status: externalGrantStatus("status").notNull().default("active"),
    // FR8b: external access grants are diligence-bounded by default.
    // Slice 1 stamps `NOW() + 90 days` at creation in `acceptInvitation`;
    // override / extension knobs land in `access-control` (slice 3).
    // Column-level default backfills any pre-FR8b rows during the
    // migration to a 90-day window so the NOT NULL constraint can land
    // without a manual data sweep.
    expiresAt: timestamp("expires_at", { withTimezone: true })
      .notNull()
      .default(sql`NOW() + INTERVAL '90 days'`),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    orgOpportunityIdx: index("eag_org_opportunity_idx").on(
      t.orgId,
      t.opportunitySlug,
    ),
    userIdx: index("eag_user_idx").on(t.userId),
    // Slice 3 will read this index for the lazy `expired` transition
    // on access checks; declaring it now avoids a follow-up migration.
    expiresAtIdx: index("eag_expires_at_idx").on(t.expiresAt),
  }),
);

export const invitations = pgTable(
  "invitations",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    workosInvitationId: text("workos_invitation_id").notNull(),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id),
    // citext so case-insensitive collision-checks against `users.email`
    // and other invitations work without `LOWER()` on every read.
    email: citext("email").notNull(),
    kind: invitationKind("kind").notNull(),
    role: invitationRole("role"),
    opportunitySlug: text("opportunity_slug"),
    invitedBy: uuid("invited_by")
      .notNull()
      .references(() => users.id),
    state: invitationState("state").notNull().default("pending"),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    workosInviteIdx: uniqueIndex("invitations_workos_invitation_id_key").on(
      t.workosInvitationId,
    ),
    orgStateIdx: index("invitations_org_state_idx").on(t.orgId, t.state),
  }),
);

export const auditEvents = pgTable(
  "audit_events",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    occurredAt: timestamp("occurred_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    eventType: text("event_type").notNull(),
    actorUserId: uuid("actor_user_id"),
    targetUserId: uuid("target_user_id"),
    orgId: uuid("org_id"),
    sourceIp: inet("source_ip"),
    userAgent: text("user_agent"),
    outcome: auditOutcome("outcome").notNull(),
    metadata: jsonb("metadata").notNull().default({}),
  },
  (t) => ({
    orgTimeIdx: index("audit_org_time_idx").on(t.orgId, t.occurredAt),
    actorTimeIdx: index("audit_actor_time_idx").on(t.actorUserId, t.occurredAt),
    targetTimeIdx: index("audit_target_time_idx").on(
      t.targetUserId,
      t.occurredAt,
    ),
    typeTimeIdx: index("audit_type_time_idx").on(t.eventType, t.occurredAt),
  }),
);

/**
 * Dedup ledger for inbound WorkOS webhook events. Each WorkOS
 * delivery carries a unique `id`; T-016's routing handler inserts
 * here before fanning out to the application handlers, and a PK
 * collision is the at-most-once signal that lets us short-circuit
 * a redelivery.
 *
 * `received_at` is the timestamp the routing layer first saw the
 * event (not the WorkOS-side `createdAt`, which lives in
 * `metadata.workosCreatedAt` if a future task wants it).
 *
 * v0.1 keeps this append-only with no GC; the table grows linearly
 * with delivered events. A future maintenance task will trim rows
 * older than the maximum WorkOS retry window (commonly 7 days).
 */
export const webhookDeliveries = pgTable("webhook_deliveries", {
  // The WorkOS event id, e.g. `event_01JABCDEF...`. Drives the
  // dedup PK; insert-on-first-delivery is the whole contract.
  eventId: text("event_id").primaryKey(),
  // Stored separately from `metadata` so analytics / dashboards can
  // group by type without parsing JSON.
  eventType: text("event_type").notNull(),
  receivedAt: timestamp("received_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

// Intentionally unused locally — kept so this barrel imports boolean from
// drizzle-orm without creating a "declared but not used" warning once we
// flesh out the lifecycle triggers. Remove when the first trigger lands.
export const _boolean = boolean;
