// Slice 2 — room-and-folders schema.
//
// Authoritative spec: `specs/ai-data-room/room-and-folders/design.md`
// §Data model. Four tables: `opportunities`, `documents`,
// `document_versions`, `document_deletions`. The seven canonical folders
// are deliberately NOT a table — they are a const enum in code
// (`@ai-data-room/api-utils/schemas/rooms#CANONICAL_FOLDERS`, ADR-003),
// identical for every org, so `documents.canonical_folder` is plain
// `text` validated at the application layer, not a pg enum.
//
// Migration `0005_room_and_folders.sql` is generated by `bun run
// db:generate` off this file. The XOR CHECK, the partial index, and the
// unique indexes are all expressible in the Drizzle DSL (drizzle-orm
// 0.36 `check()` + `uniqueIndex().where()`), so — unlike slice 1's
// `0001` — no hand-written companion migration is needed.
//
// ── Reconciliations vs design.md §Data model (flagged in PR) ──────────
//
// 1. **`document_versions.org_id`** — the design's `document_versions`
//    table has no `org_id`. The tenant-isolation mechanism (slice 10 /
//    ADR-011), which post-dates this design and gates slice 2, isolates
//    every per-tenant table with a `WHERE org_id = $1` predicate driven
//    by `TENANT_SCOPED_TABLES`. A scoped repo can only extend
//    `ScopedRepo` (reads via `this.scoped(col)`, writes via
//    `stampOrgId`) if its table carries `org_id`. The room brief lists
//    `document_versions` among the tables that MUST be tenant-scoped, so
//    we denormalise `org_id` onto it — matching how every other scoped
//    table (`org_memberships`, `invitations`, …) carries a direct
//    `org_id` → `organizations.id`. Isolation is enforced at the
//    application layer per ADR-011 (the scoped factory + property test),
//    exactly as for the slice-1 tables; we deliberately do NOT add a
//    composite `(document_id, org_id)` tenant FK, because no other
//    scoped table uses one and ADR-011 chose app-layer, not DB-level,
//    isolation.
//
// Everything else follows the design data model verbatim — including
// `sha256 bytea` (the `bytea`↔hex-string mapping is a repo-boundary
// concern handled in T-004) and `documents.current_version_id` as a
// real FK to `document_versions.id` (a circular reference the migrator
// resolves with a trailing `ALTER TABLE … ADD CONSTRAINT`).

import {
  type AnyPgColumn,
  bigint,
  check,
  customType,
  index,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

import { organizations, users } from "./auth";

// `bytea` — raw bytes. Postgres-specific; Drizzle ships no column helper,
// so declare it via `customType` (same escape hatch as `citext` in
// `auth.ts`). Holds the 32-byte sha-256 digest of a version's contents
// (FR12). The JS boundary is a `Buffer`; the hex-string ⇄ bytea mapping
// used by the domain DTO (`sha256: string`) is applied in the repo
// (T-004), not here.
const bytea = customType<{ data: Buffer }>({
  dataType: () => "bytea",
});

// ── Enums ──────────────────────────────────────────────────────────────
export const opportunityStatus = pgEnum("opportunity_status", [
  "active",
  "archived",
]);

export const folderKind = pgEnum("folder_kind", ["canonical", "opportunity"]);

// Full document lifecycle. `draft` (design §Upload pipeline) precedes
// `active`: an initiated-but-not-completed upload; excluded from all
// listings. `hard_deleted` is the post-retention terminal state (see
// `document_deletions`).
export const documentState = pgEnum("document_state", [
  "draft",
  "active",
  "soft_deleted",
  "hard_deleted",
]);

// ── Tables ─────────────────────────────────────────────────────────────

/**
 * An Opportunity subroom under `Opportunities/` (FR4–FR7). Names are
 * unique per org; archival (FR6) sets `status='archived'` + `archived_at`
 * and starts the 90-day retention clock swept in T-010.
 */
export const opportunities = pgTable(
  "opportunities",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id),
    // Slug uniqueness/format (1–64, `[A-Za-z0-9_-]+`) is enforced at the
    // application layer (`OpportunitySlugSchema`); the DB guarantees only
    // per-org uniqueness via the index below.
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    status: opportunityStatus("status").notNull().default("active"),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    createdBy: uuid("created_by")
      .notNull()
      .references(() => users.id),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // FR4: names unique within the org.
    orgSlugIdx: uniqueIndex("opportunities_org_slug_key").on(t.orgId, t.slug),
    // Fast nav: list the org's live subrooms without scanning archived.
    orgActiveIdx: index("opportunities_org_active_idx")
      .on(t.orgId)
      .where(sql`status = 'active'`),
  }),
);

/**
 * A logical document living in exactly one folder — either one of the
 * seven canonical folders (`folder_kind='canonical'`, `canonical_folder`
 * set) or an Opportunity subroom (`folder_kind='opportunity'`,
 * `opportunity_id` set). The XOR is enforced by the CHECK below, matching
 * design §Data model. `current_version_id` denormalises the latest
 * version for listing speed.
 */
export const documents = pgTable(
  "documents",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id),
    folderKind: folderKind("folder_kind").notNull(),
    // One of `CANONICAL_FOLDERS`; null iff `folder_kind='opportunity'`.
    // Plain text, not an enum — the canonical set lives in code (ADR-003).
    canonicalFolder: text("canonical_folder"),
    opportunityId: uuid("opportunity_id").references(() => opportunities.id),
    displayName: text("display_name").notNull(),
    // Circular FK → document_versions.id (defined below). Nullable: a
    // `draft` document has no completed version yet. The migrator emits
    // this as a trailing ALTER since the target table is created after.
    // The `: AnyPgColumn` return annotation breaks the TS inference cycle
    // between `documents` and `documentVersions` (they reference each
    // other); without it tsc reports TS7022 implicit-any.
    currentVersionId: uuid("current_version_id").references(
      (): AnyPgColumn => documentVersions.id,
    ),
    state: documentState("state").notNull().default("draft"),
    softDeletedAt: timestamp("soft_deleted_at", { withTimezone: true }),
    createdBy: uuid("created_by")
      .notNull()
      .references(() => users.id),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // Listing indexes (design §Data model): canonical-folder browse and
    // opportunity browse, both filtered by state.
    canonicalListingIdx: index("documents_canonical_listing_idx").on(
      t.orgId,
      t.folderKind,
      t.canonicalFolder,
      t.state,
    ),
    opportunityListingIdx: index("documents_opportunity_listing_idx").on(
      t.orgId,
      t.opportunityId,
      t.state,
    ),
    // Exactly one of (canonical_folder, opportunity_id) is non-null, and
    // it agrees with folder_kind. The DB backstop for the domain
    // `DocumentSchema.superRefine`.
    folderXor: check(
      "documents_folder_kind_xor",
      sql`(
        ${t.folderKind} = 'canonical'
          AND ${t.canonicalFolder} IS NOT NULL
          AND ${t.opportunityId} IS NULL
      ) OR (
        ${t.folderKind} = 'opportunity'
          AND ${t.opportunityId} IS NOT NULL
          AND ${t.canonicalFolder} IS NULL
      )`,
    ),
  }),
);

/**
 * One immutable version per upload — even a same-name re-upload creates a
 * new version (FR13/FR15), never an overwrite. Append-only (NFR8).
 * `org_id` is the tenant-scoping column (see reconciliation #1 in the
 * file header). `document_id` cascades so a hard-deleted document takes
 * its versions with it.
 */
export const documentVersions = pgTable(
  "document_versions",
  {
    id: uuid("id")
      .primaryKey()
      .default(sql`gen_random_uuid()`),
    documentId: uuid("document_id")
      .notNull()
      // `: AnyPgColumn` breaks the same documents ⇄ document_versions TS
      // inference cycle noted on `documents.current_version_id`.
      .references((): AnyPgColumn => documents.id, { onDelete: "cascade" }),
    orgId: uuid("org_id")
      .notNull()
      .references(() => organizations.id),
    versionNumber: bigint("version_number", { mode: "number" }).notNull(),
    originalFilename: text("original_filename").notNull(),
    mimeType: text("mime_type").notNull(),
    // `mode: "number"` is load-bearing: node-postgres returns int8 as a
    // string by default, which the domain `DocumentVersionSchema`
    // (`sizeBytes: z.number()`) would reject. 100 MB (FR10) is well
    // within Number.MAX_SAFE_INTEGER.
    sizeBytes: bigint("size_bytes", { mode: "number" }).notNull(),
    sha256: bytea("sha256").notNull(),
    s3Key: text("s3_key").notNull(),
    s3VersionId: text("s3_version_id"),
    uploadedBy: uuid("uploaded_by")
      .notNull()
      .references(() => users.id),
    uploadedAt: timestamp("uploaded_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // Monotonic version numbers per document (FR15).
    docVersionIdx: uniqueIndex("document_versions_doc_version_key").on(
      t.documentId,
      t.versionNumber,
    ),
  }),
);

/**
 * Audit-adjacent record retained past hard-delete for forensic
 * reconstruction (design §Data model). Deliberately carries NO FK to
 * `documents` — the row outlives the document it references (the
 * document row is gone by the time this is the system of record) — and
 * NO filename, to avoid leaking PII into the retention record.
 */
export const documentDeletions = pgTable("document_deletions", {
  id: uuid("id")
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  // Intentionally not a FK: the referenced document may already be
  // hard-deleted (design §Data model).
  documentId: uuid("document_id").notNull(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => organizations.id),
  softDeletedBy: uuid("soft_deleted_by")
    .notNull()
    .references(() => users.id),
  hardDeletedAt: timestamp("hard_deleted_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});
